INSERT INTO materials (id, type_materials, id_etat) VALUES
    (1, 'Ordinateur portable', 6),
    (2, 'Imprimante laser', 10),
    (3, 'Écran LCD 24 pouces', 14),
    (4, 'Clavier sans fil', 3),
    (5, 'Souris optique', 18),
    (6, 'Routeur WiFi', 5),
    (7, 'Casque audio USB', 9),
    (8, 'Webcam HD', 12),
    (9, 'Disque dur externe', 8),
    (10, 'Tablette graphique', 11),
    (11, 'Enceintes stereo', 20),
    (12, 'Scanner a plat', 16),
    (13, 'Serveur rack', 4),
    (14, 'Switch réseau 24 ports', 7),
    (15, 'Lecteur de code-barres', 19),
    (16, 'Projecteur video', 2),
    (17, 'Routeur VPN', 15),
    (18, 'Haut-parleur Bluetooth', 17),
    (19, 'Imprimante à jet d encre', 13),
    (20, 'Laptop de jeu', 1),
    (21, 'Moniteur 4K', 6),
    (22, 'Trackball', 10),
    (23, 'Stylo optique', 14),
    (25, 'Microphone USB', 18),
    (26, 'Serveur tour', 5),
    (27, 'Switch réseau 48 ports', 9),
    (28, 'Scanner a documents', 12),
    (29, 'Enregistreur vocal', 8),
    (30, 'Routeur industriel', 11);
