insert into Personnel (id, nom_personnel, fonction) values (1, 'Maximo Iacopini', 'Electrical Engineer');
insert into Personnel (id, nom_personnel, fonction) values (2, 'Jordan Groneway', 'Accounting Assistant II');
insert into Personnel (id, nom_personnel, fonction) values (3, 'Amery Boothebie', 'General Manager');
insert into Personnel (id, nom_personnel, fonction) values (4, 'Dennie McKearnen', 'Staff Accountant I');
insert into Personnel (id, nom_personnel, fonction) values (5, 'Allayne Arents', 'Tax Accountant');
insert into Personnel (id, nom_personnel, fonction) values (6, 'Gleda Morrieson', 'Professor');
insert into Personnel (id, nom_personnel, fonction) values (7, 'Flossy Fleetwood', 'Web Developer II');
insert into Personnel (id, nom_personnel, fonction) values (8, 'Langsdon Osmar', 'Librarian');
insert into Personnel (id, nom_personnel, fonction) values (9, 'Jarrod Ewington', 'Analog Circuit Design manager');
insert into Personnel (id, nom_personnel, fonction) values (10, 'Bevvy Calltone', 'Structural Analysis Engineer');
insert into Personnel (id, nom_personnel, fonction) values (11, 'Joe Cline', 'Computer Systems Analyst I');
insert into Personnel (id, nom_personnel, fonction) values (12, 'Morgan Beynon', 'Actuary');
insert into Personnel (id, nom_personnel, fonction) values (13, 'Roarke Sholem', 'Administrative Officer');
insert into Personnel (id, nom_personnel, fonction) values (14, 'Benn Teague', 'Graphic Designer');
insert into Personnel (id, nom_personnel, fonction) values (15, 'Daile Zini', 'Engineer II');
insert into Personnel (id, nom_personnel, fonction) values (16, 'Godiva Roo', 'Nuclear Power Engineer');
insert into Personnel (id, nom_personnel, fonction) values (17, 'Trent Landrieu', 'Assistant Manager');
insert into Personnel (id, nom_personnel, fonction) values (18, 'Jere Grouen', 'Nurse');
insert into Personnel (id, nom_personnel, fonction) values (19, 'Carlye Rodenborch', 'Accounting Assistant I');
insert into Personnel (id, nom_personnel, fonction) values (20, 'Mack Brasse', 'Office Assistant III');
